{
    "name": "Website Rentals",
    "description": "Exposes rentals in the portal.",
    "author": "Mainframe Monkey",
    "website": "http://www.mainframemonkey.com",
    "category": "Website",
    "version": "14.0.2.0",
    "license": "LGPL-3",
    "depends": [
        "sale",
        "sale_management",
        "sale_renting",
        "stock",
        "uom",
        "web",
        "website",
        "website_sale",
        "sale_stock_renting",
    ],
    "images": [],
    "demo": [],
    "qweb": [
        "static/src/components/*.xml",
    ],
    "data": [
        "views/assets.xml",
        "views/product_templates.xml",
        "views/website_sale_templates.xml",
    ],
}
